# Generated by Django 4.0.3 on 2022-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
