# Generated by Django 4.0.3 on 2022-03-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_message_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='raw_data',
        ),
    ]
