# Generated by Django 4.0.3 on 2022-03-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_message_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.chat'),
            preserve_default=False,
        ),
    ]
