# Generated by Django 4.0.3 on 2022-03-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_message_client_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hash_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
