# Generated by Django 4.0.3 on 2022-03-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_client_hash_link_client_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'чат', 'verbose_name_plural': 'чаты'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
