# Generated by Django 4.0.3 on 2022-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_chat_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='keyboard_status',
            field=models.IntegerField(choices=[(0, 'No Kbd'), (1, 'Change Chat'), (2, 'Chats List')], default=1),
        ),
    ]
